name: Lint and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8.0

      - name: Unit tests with coverage
        run: task test-coverage

      - name: Integration tests
        run: task test-integration

      - name: Submit coverage
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage-resilience.out,./coverage-adapter.out,./coverage-integration.out
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ env.GITHUB_REPOSITORY }}
